version: "3.9"

services:

  db:
    image: mariadb:11

    container_name: drupal-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

    volumes:
      - db_data:/var/lib/mysql

  drupal:

    build: .

    container_name: drupal-web

    depends_on:
      - db

    ports:
      - "8080:80"

    restart: always

    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal

volumes:

  db_data: