<?php

/**
 * @file
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\radix\Hook\FieldsetHooks;

/**
 * @file
 * Theme and preprocess functions for fieldsets.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Alters theme suggestions for fieldsets within Views.
 */
#[LegacyHook]
function radix_theme_suggestions_fieldset_alter(array &$suggestions, array $variables) {
  FieldsetHooks::themeSuggestionsFieldsetAlter($suggestions, $variables);
}
