<?php

/**
 * @file
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\radix\Hook\TaxonomyHooks;

/**
 * @file
 * Theme and preprocess functions for taxonomy and vocabularies.
 */

/**
 * Implements hook_theme_suggestions_taxonomy_term_alter().
 */
#[LegacyHook]
function radix_theme_suggestions_taxonomy_term_alter(array &$suggestions, array $variables) {
  TaxonomyHooks::themeSuggestionsTaxonomyTermAlter($suggestions, $variables);
}
