<?php

/**
 * @file
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\radix\Hook\ViewHooks;

/**
 * @file
 * Theme and preprocess functions for views.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
#[LegacyHook]
function radix_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  ViewHooks::themeSuggestionsViewsViewAlter($suggestions, $variables);
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
#[LegacyHook]
function radix_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables) {
  ViewHooks::themeSuggestionsViewsViewUnformattedAlter($suggestions, $variables);
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Alters theme suggestions for exposed forms in Views.
 */
#[LegacyHook]
function radix_theme_suggestions_views_exposed_form_alter(array &$suggestions, array $variables) {
  ViewHooks::themeSuggestionsViewsExposedFormAlter($suggestions, $variables);
}
